# Generated by Django 4.0.6 on 2022-07-17 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores_modelo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 18, 24, 20, 734699, tzinfo=utc)),
        ),
    ]
