# Generated by Django 4.0.6 on 2022-07-17 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('valores', '0003_alter_valores_modelo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores_modelo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
